<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>LedgerForge.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Npgsql" Version="8.0.6" />
    <PackageReference Include="RabbitMQ.Client" Version="6.8.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\LedgerForge.Domain\LedgerForge.Domain.csproj" />
    <ProjectReference Include="..\LedgerForge.Application\LedgerForge.Application.csproj" />
  </ItemGroup>
</Project>